Matrix sharps, matrix flats, subdivision, and link
AlgebraicJulia/CombinatorialSpaces.jl pull request #59
Opened 2023-07-01 00:22 UTC by lukem12345

This PR implements subdivision as a data migration, matrix versions of the sharp and flat operators, an alternative weighting scheme for the sharp operator, and the star, closed star, and link operators from S68 of Munkres' Elementary Algebraic Topology.

_Some of these changes may need to get shifted to a different branch_. In particular, subdivision cannot yet automatically compute barycenters of simplices until the `attrMigr` branch of Catlab is merged. Relatedly, refactoring the DualComplex schemas as a data migration that "remembers" e.g. which triangle a supporting dual triangle came from also depends on this functionality.

The star, closed star, and link operators were implemented as higher-level helper functions which will become more useful as 3D operators are becoming supported. This (not-Hodge) star essentially recursively computes cofaces, which is a common pattern in this codebase. e.g. grabbing all tetrahedra around a vertex v is simply star(v).

While developing the matrix version of the sharp operator, it was noted that the sharp of an EForm generated by a constant form would generate a primal vector field with the correct direction, but of incorrect magnitude. In particular, vectors with few neighbors would be too small, and those with many neighbors would be too large. By adjusting replacing the weighting denominator in Eq. 5.8.1 from Hirani with | star v | instead of | sigma n |, we successfully recover the original field (up to floating point error).

As implemented at time of writing, the matrix-flat multiplied by a vector X of `SVector`s will return a vector of length 1 `SArray`s. When X is wrapped in `DualVectorField()`, this result is automatically `reinterpret`ed to a vector of floats. This fix is a little unusual, but I am not sure how to structure the flat matrix to avoid this.

2023-08-07 19:05 UTC, lukem12345 commented
Due to scheduling, this PR consists of a few disparate features:
- Subdivision of non-embedded 1D delta sets w/o point attributes
- Star, Closed Star, and Link operators from Munkres. a.k.a. "topological helper functions"
- Matrix version of sharp
- Matrix version of flat
- Alternate weighting scheme for flat

All these features have tests.

When considering which features to merge, we should note:
- Only 1D subdivision-as-data-migration is supported. Due to outstanding [Catlab PR #823](https://github.com/AlgebraicJulia/Catlab.jl/pull/823), barycentric and other automatic weighting of the `point` attribute is blocked. Although the current `subdivide` functions pass tests, perhaps this feature should live on a different branch for the time being.
- Star, Closed Star, and Link are implemented for vertex input only. I believe that the current implementation is helpful as-is, however.
- See my previous comment for the return type of the matrix version of flat
- The Desbrun weighting scheme is rather poor, and I don't imagine it would be used in practice. However, it may still be nice to offer this for completeness' sake.
- Likewise, I believe that the Hirani weighting scheme is inferior to the "Alternate" weighting scheme due to behavior mentioned in my previous comment. It may be best to change the default weighting scheme to "Alternate."

2024-02-17 16:21 UTC, lukem12345 commented
Todo:
- [] Use QR decomposition in the new sharp operator

2024-02-17 17:27 UTC, jpfairbanks commented
I think you are probably better off with GMRES or PCG because the QR decomp will be dense.

2024-02-17 17:33 UTC, lukem12345 commented
Oh, the QR decomp is just for the tiny (3×3 in R3, 3×2 in R2) matrices. For
each triangle T, I split this tiny matrix into its rows, and place each row
in the corresponding position in the (num-triangles × num-edges) sparse
matrix.

Maybe QR decomposition is not what I want here,  since the application of
the entire operation is still just sparse matrix multiplication.

On Sat, Feb 17, 2024, 12:28 PM James ***@***.***> wrote:

> I think you are probably better off with GMRES or PCG because the QR
> decomp will be dense.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AlgebraicJulia/CombinatorialSpaces.jl/pull/59#issuecomment-1950262936>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQYHBYINJO6PUT3DOUZAC53YUDSCJAVCNFSM6AAAAAAZ2N2GFOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNJQGI3DEOJTGY>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2024-02-27 16:25 UTC, olynch requested changes
I've left some comments. The comments with :green_circle: should be addressed in a future PR, the comments with :red_circle: should be addressed in this PR.

2024-02-27 16:25 UTC, olynch commented on src/FastDEC.jl
> +function wedge_pd_01_mat(sd::HasDeltaSet)
This could be generalized by taking as an argument the type of matrix to create. Also, we could have a type `WedgeProduct` which wrapped `sd`. When applied to arguments, this would dynamically compute the wedge product. But then this function could be written as something like:

`concretize(w::WedgeProduct, A::Type{<:AbstractMatrix})::A`

Then we can reuse `concretize` for all sorts of similar problems. This is beyond the scope of this PR though: I'll make an issue for this.

2024-02-27 16:25 UTC, olynch commented on src/Meshes.jl
> +"""    function tri_345()
what is a 3-4-5 triangle: can you add a link to this docstring?

2024-02-27 16:25 UTC, olynch commented on src/Meshes.jl
> +"""    function fri_345()
Why is this called `fri`?

2024-02-27 16:25 UTC, olynch commented on src/Meshes.jl
> +Return the primal and dual mesh of a right triangle with unit hypotenuse.
This does not uniquely specify the triangle. Do you mean an isosceles right triangle?

2024-02-27 16:25 UTC, olynch commented on src/SimplicialSets.jl
> +Return a vector of simplices of dimensions 0 to n.
This docstring was confusing: you mean returns a vector where the element at index `i` is a set of simplices of dimension `i - 1`. This should probably be a tuple rather than a vector, and you should wrap it with a struct with a good name, like

```
struct Simplices{Ts <: Tuple}
  by_dimension::Ts
end
```

2024-02-27 16:25 UTC, olynch commented on src/FastDEC.jl
> +function wedge_pd_01_mat(sd::HasDeltaSet)
:green_circle:

2024-02-27 16:25 UTC, olynch commented on src/Meshes.jl
> +"""    function tri_345()
:red_circle:

2024-02-27 16:25 UTC, olynch commented on src/Meshes.jl
> +"""    function fri_345()
:red_circle:

2024-02-27 16:25 UTC, olynch commented on src/Meshes.jl
> +Return the primal and dual mesh of a right triangle with unit hypotenuse.
:red_circle:

2024-02-27 16:25 UTC, olynch commented on src/SimplicialSets.jl
> +Return a vector of simplices of dimensions 0 to n.
:green_circle:

2024-02-27 22:15 UTC, merged