3D Differential Operators
AlgebraicJulia/CombinatorialSpaces.jl pull request #60
Opened 2023-08-15 22:00 UTC by lukem12345

This pull request adds support for 3D differential operators via a "DeltaDualComplex" strategy that is analogous to the 1D and 2D cases.

Before merging:

- [ ] Test all hodge star operators
- [ ] Implement wedge product
- [ ] Implement flat and sharp by dispatching on dimension of the DeltaDualComplex

2024-04-26 20:13 UTC, lukem12345 commented
On merging, I will open an issue to implement the 1-2 wedge.

2024-06-13 21:13 UTC, GeorgeR227 requested changes

2024-06-13 21:13 UTC, GeorgeR227 commented on test/DiscreteExteriorCalculus.jl
> +@test all(dual_volume(3,s,1:24) .≈ regular_tetrahedron_volume(2√2)/24)
Tighten the bounds on this, since this just seems to be a rounding error.

2024-06-14 16:48 UTC, merged

2025-05-27 21:30 UTC, lukem12345 commented
See #163